import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ReactNode } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <video
          autoPlay
          loop
          muted
          className="absolute top-0 left-0 w-full h-full object-cover z-0"
        >
          <source src="/images/rain.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        <main className="relative z-30 max-w-8xl max-h-7xl mx-auto my-8 p-6 bg-slate-300 opacity-95">
          {children}
        </main>
      </body>
    </html>
  );
}